//
// The Calculator service is easy to use.
//
// Examples
// --------
//
//     x = calc.add(10, 30)
//     # x == 40
//
//     y = calc.subtract(44, 10)
//     # y == 34

interface Calculator {
    // Adds two numbers together and returns the result   
    add(a float, b float) float
        
    // Subtracts b from a and returns the result
    subtract(a float, b float) float
}